apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: volume-claim
      containers:
        - name: todo
          image: maroctamorg/todo:latest
          volumeMounts:
            - name: volume
              mountPath: /srv/todo/public/db
